### ISSUE TITLE
not in build: chrome://flags/#enable-webrtc-pipewire-capturer

### ISSUE THREAD

**Issue by 22-all** [clickot/ungoogled-chromium-portable-build#1]
The chrome://flags/#enable-webrtc-pipewire-capturer flag is not available in the ungoogled-chromium-portable-build, as well as the appimage. It is, however, present in the ungoogled-chromium flatpak, for example.

There might be a good reason for that, but as the flag is necessary for screen sharing in Wayland sessions, it would be great if   it could be includes at some stage.

**Comment by clickot** [comment]
I did not take any measures converning flags and executed the build procedure in https://github.com/ungoogled-software/ungoogled-chromium-portablelinux "as is". The only thing my procedure adds is to provide a docker image to build in it that has a complete clang-15 toolchain installed. So i don't really know how to handle your issue. Maybe it makes sense to open this issue in https://github.com/ungoogled-software/ungoogled-chromium-portablelinux.

**Comment by clickot** [comment]
thanks @22-all , i close this isue
